import {
  applySettingOverrides,
  buildDefaultPartSettings,
  type ParameterValue,
} from "../domain/patchUi";
import { summitPatchProposalSchema, type SummitPatchProposal } from "../domain/schemas";

export type DemoConfig = {
  id: string;
  displayName: string;
  patchName: string;
  name: string;
  category: SummitPatchProposal["patch"]["category"];
  description: string;
  keywords: string[];
  values: Readonly<Record<string, ParameterValue>>;
};

const shared = {
  "filter.shape": "LP",
  "filter.slope": "24 dB",
  "amp.delay": 0,
} as const;

export const demoConfigs: DemoConfig[] = [
  {
    id: "progressive-house-pluck",
    displayName: "Progressive House Pluck",
    patchName: "Prog House Plk",
    name: "Progressive House Pluck",
    category: "pluck",
    description: "Pluck progressive-house brillante, corto e largo.",
    keywords: ["pluck", "progressive", "sharp", "brillante", "transient"],
    values: {
      ...shared,
      "osc1.range": "8'",
      "osc1.wave": "Sawtooth",
      "osc1.shape": 8,
      "osc2.range": "8'",
      "osc2.wave": "Sawtooth",
      "osc2.fine": 9,
      "osc3.range": "4'",
      "osc3.wave": "Square/Pulse",
      "osc3.fine": -6,
      "mixer.osc1.level": 235,
      "mixer.osc2.level": 172,
      "mixer.osc3.level": 64,
      "mixer.noise.level": 14,
      "filter.frequency": 185,
      "filter.resonance": 42,
      "filter.overdrive": 18,
      "filter.modEnv1Depth": 42,
      "amp.attack": 0,
      "amp.decay": 42,
      "amp.sustain": 18,
      "amp.release": 28,
      "modEnv1.attack": 0,
      "modEnv1.decay": 38,
      "modEnv1.sustain": 0,
      "modEnv1.release": 19,
      "lfo1.rate": 92,
      "fx.chorus.level": 45,
      "fx.delay.level": 36,
      "fx.reverb.level": 31,
      "osc.common.drift": 7,
      "osc1.bendRange": 12,
      "voice.mode": "Poly",
      "voice.unison": "2",
      "voice.unisonDetune": 31,
      "voice.spread": 48,
    },
  },
  {
    id: "warm-analogue-pad",
    displayName: "Warm Analogue Pad",
    patchName: "Warm Analog Pad",
    name: "Warm Analogue Pad",
    category: "pad",
    description: "Pad analogico caldo, lento e delicatamente instabile.",
    keywords: ["pad", "cinematic", "warm", "caldo", "lento"],
    values: {
      ...shared,
      "osc1.range": "8'",
      "osc1.wave": "Sawtooth",
      "osc1.shape": -9,
      "osc2.range": "8'",
      "osc2.wave": "Triangle",
      "osc2.fine": -11,
      "osc3.range": "16'",
      "osc3.wave": "Sawtooth",
      "osc3.fine": 7,
      "mixer.osc1.level": 212,
      "mixer.osc2.level": 188,
      "mixer.osc3.level": 105,
      "mixer.noise.level": 20,
      "filter.frequency": 118,
      "filter.resonance": 19,
      "filter.overdrive": 12,
      "filter.modEnv1Depth": 17,
      "filter.lfo1Depth": 22,
      "amp.attack": 82,
      "amp.decay": 76,
      "amp.sustain": 108,
      "amp.release": 101,
      "modEnv1.attack": 69,
      "modEnv1.decay": 80,
      "modEnv1.sustain": 61,
      "modEnv1.release": 92,
      "lfo1.rate": 43,
      "lfo1.fadeTime": 54,
      "lfo2.rate": 31,
      "fx.chorus.level": 69,
      "fx.delay.level": 22,
      "fx.reverb.level": 76,
      "osc.common.drift": 29,
      "voice.unison": "4",
      "voice.unisonDetune": 44,
      "voice.spread": 92,
    },
  },
  {
    id: "reese-bass",
    displayName: "Reese Bass",
    patchName: "Reese Bass",
    name: "Reese Bass",
    category: "bass",
    description: "Reese bass scuro con centro mono controllato.",
    keywords: ["reese", "bass", "basso", "dark", "scuro", "mono"],
    values: {
      ...shared,
      "osc1.range": "16'",
      "osc1.wave": "Sawtooth",
      "osc1.shape": -14,
      "osc2.range": "16'",
      "osc2.wave": "Sawtooth",
      "osc2.fine": -18,
      "osc3.range": "16'",
      "osc3.wave": "Square/Pulse",
      "osc3.fine": 13,
      "mixer.osc1.level": 255,
      "mixer.osc2.level": 220,
      "mixer.osc3.level": 96,
      "mixer.noise.level": 6,
      "filter.frequency": 83,
      "filter.resonance": 31,
      "filter.overdrive": 55,
      "filter.modEnv1Depth": 24,
      "amp.attack": 2,
      "amp.decay": 70,
      "amp.sustain": 112,
      "amp.release": 24,
      "fx.chorus.level": 18,
      "fx.delay.level": 0,
      "fx.reverb.level": 7,
      "fx.distortion.level": 63,
      "osc.common.drift": 14,
      "voice.mode": "MonoLG",
      "voice.unison": "2",
      "voice.unisonDetune": 37,
      "voice.spread": 18,
      "glide.time": 42,
    },
  },
  {
    id: "fm-bell",
    displayName: "FM Bell",
    patchName: "FM Bell",
    name: "FM Bell",
    category: "bell",
    description: "Campana FM metallica con brillantezza sensibile alla velocity.",
    keywords: ["bell", "campana", "metal", "metallic", "fm", "velocity"],
    values: {
      ...shared,
      "osc1.range": "8'",
      "osc1.wave": "Sine",
      "osc2.range": "4'",
      "osc2.wave": "Sine",
      "osc2.coarse": 7,
      "osc3.range": "2'",
      "osc3.wave": "Sine",
      "osc3.coarse": 12,
      "mixer.osc1.level": 220,
      "mixer.osc2.level": 128,
      "mixer.osc3.level": 86,
      "mixer.noise.level": 2,
      "filter.frequency": 221,
      "filter.resonance": 49,
      "filter.overdrive": 5,
      "amp.attack": 0,
      "amp.decay": 89,
      "amp.sustain": 4,
      "amp.release": 74,
      "modEnv2.attack": 0,
      "modEnv2.decay": 64,
      "modEnv2.sustain": 0,
      "modEnv2.release": 82,
      "fx.chorus.level": 12,
      "fx.delay.level": 30,
      "fx.reverb.level": 58,
      "osc.common.drift": 2,
      "voice.mode": "Poly",
    },
  },
  {
    id: "supersaw-lead",
    displayName: "Supersaw Lead",
    patchName: "Supersaw Lead",
    name: "Supersaw Lead",
    category: "lead",
    description: "Lead supersaw ampio e presente con movimento stereo.",
    keywords: ["supersaw", "lead", "wide", "ampio", "stereo", "saw"],
    values: {
      ...shared,
      "osc1.range": "8'",
      "osc1.wave": "Sawtooth",
      "osc1.shape": 22,
      "osc2.range": "8'",
      "osc2.wave": "Sawtooth",
      "osc2.fine": -14,
      "osc3.range": "8'",
      "osc3.wave": "Sawtooth",
      "osc3.fine": 17,
      "mixer.osc1.level": 255,
      "mixer.osc2.level": 232,
      "mixer.osc3.level": 198,
      "mixer.noise.level": 10,
      "filter.frequency": 204,
      "filter.resonance": 28,
      "filter.overdrive": 26,
      "filter.modEnv1Depth": 31,
      "amp.attack": 5,
      "amp.decay": 58,
      "amp.sustain": 103,
      "amp.release": 46,
      "lfo1.rate": 74,
      "fx.chorus.level": 78,
      "fx.delay.level": 42,
      "fx.reverb.level": 37,
      "osc.common.drift": 11,
      "voice.mode": "Poly2",
      "voice.unison": "8",
      "voice.unisonDetune": 55,
      "voice.spread": 112,
    },
  },
];

function setupInstructions(settings: ReturnType<typeof buildDefaultPartSettings>) {
  const value = (parameterId: string) =>
    [...settings.panelControls, ...settings.menuSettings].find(
      (setting) => setting.parameterId === parameterId,
    )?.displayValue ?? "—";
  return [
    {
      order: 1,
      area: "Oscillators",
      instruction: `Oscillator 1 → Range → ${value("osc1.range")}; Wave → ${value("osc1.wave")}.`,
      parameterIds: ["osc1.range", "osc1.wave"],
    },
    {
      order: 2,
      area: "Mixer",
      instruction: `Mixer → Osc 1 ${value("mixer.osc1.level")}, Osc 2 ${value("mixer.osc2.level")}, Osc 3 ${value("mixer.osc3.level")}.`,
      parameterIds: ["mixer.osc1.level", "mixer.osc2.level", "mixer.osc3.level"],
    },
    {
      order: 3,
      area: "Filter",
      instruction: `Filter → Frequency → ${value("filter.frequency")}; Resonance → ${value("filter.resonance")}.`,
      parameterIds: ["filter.frequency", "filter.resonance", "filter.overdrive"],
    },
    {
      order: 4,
      area: "Envelopes",
      instruction: `Amp Envelope → A ${value("amp.attack")}, D ${value("amp.decay")}, S ${value("amp.sustain")}, R ${value("amp.release")}.`,
      parameterIds: ["amp.attack", "amp.decay", "amp.sustain", "amp.release"],
    },
    {
      order: 5,
      area: "LFO",
      instruction: `LFO 1 → Rate → ${value("lfo1.rate")}.`,
      parameterIds: ["lfo1.rate", "lfo1.fadeTime"],
    },
    {
      order: 6,
      area: "Modulation",
      instruction: "Apri Mod Matrix e configura soltanto gli slot evidenziati.",
      parameterIds: ["filter.modEnv1Depth", "filter.lfo1Depth"],
    },
    {
      order: 7,
      area: "Effects",
      instruction: `Effects → Chorus ${value("fx.chorus.level")}, Delay ${value("fx.delay.level")}, Reverb ${value("fx.reverb.level")}.`,
      parameterIds: ["fx.chorus.level", "fx.delay.level", "fx.reverb.level"],
    },
    {
      order: 8,
      area: "Voice / other",
      instruction: `Voice → Mode → ${value("voice.mode")}; verifica Glide e Arpeggiator.`,
      parameterIds: ["voice.mode", "glide.time", "arp.on"],
    },
  ];
}

export function buildDemoProposal(config: DemoConfig, targetSound?: string): SummitPatchProposal {
  const settings = applySettingOverrides(buildDefaultPartSettings(), config.values);
  return summitPatchProposalSchema.parse({
    schemaVersion: "1.0.0",
    proposalId: `demo-${config.id}-${Date.now()}`,
    createdAt: new Date().toISOString(),
    targetFirmware: "2.1",
    patch: {
      name: config.patchName,
      mode: "single",
      category: config.category,
      description: config.description,
      targetSound: targetSound || config.description,
    },
    analysis: {
      soundRole: config.category,
      synthesisHypothesis: `Patch ${config.displayName} costruita da valori catalogati e controlli fisici verificati.`,
      oscillatorStrategy: "Tre oscillatori bilanciati secondo il ruolo timbrico della demo.",
      filterStrategy: "Filtro e inviluppo sono coordinati per preservare attacco e leggibilità.",
      envelopeStrategy: "Amp e Mod Envelope definiscono il profilo dinamico della patch.",
      modulationStrategy: "Routing espressivi limitati a sorgenti e destinazioni ufficialmente verificate.",
      effectsStrategy: "Chorus, delay e reverb sono dosati per profondità senza coprire il centro.",
      overallConfidence: 0.82,
      assumptions: ["Init Patch e firmware Summit 2.1.", "Taratura finale all'ascolto sullo strumento."],
      uncertainties: ["La demo non sostituisce il confronto sul Summit fisico."],
    },
    parts: [
      {
        part: "A",
        ...settings,
        modulationMatrix: [
          {
            slot: 1,
            sourceA: "velocity",
            destination: "filter.frequency",
            depth: config.category === "bell" ? 38 : 18,
            rationale: "La dinamica apre il filtro.",
          },
          {
            slot: 2,
            sourceA: "lfo1.bipolar",
            destination: "osc1.shape",
            depth: config.category === "pad" ? 16 : 7,
            rationale: "Movimento timbrico misurato.",
          },
        ],
        fxModulationMatrix: [
          {
            slot: 1,
            sourceA: "lfo3.bipolar",
            destination: "fx.chorus.level",
            depth: config.category === "lead" ? 18 : 8,
            rationale: "Movimento stereo controllato.",
          },
        ],
      },
    ],
    setupInstructions: setupInstructions(settings),
    auditionGuide: {
      recommendedNotes: config.category === "bass" ? ["C1", "G1", "C2"] : ["C3", "E3", "G3", "C4"],
      recommendedVelocity: "Prova 50, 90 e 120",
      recommendedPlayingStyle: config.category === "pluck" ? "Note corte e accordi sincopati" : "Note singole e accordi sostenuti",
      whatToListenFor: ["Attacco", "centro", "coda degli effetti", "risposta alla velocity"],
    },
    refinements: [
      {
        problem: "Troppo brillante",
        suggestedChanges: [{ parameterId: "filter.frequency", operation: "decrease", amount: 20 }],
      },
    ],
    alternatives: [
      {
        name: "Più scura",
        explanation: "Riduci il cutoff.",
        changedParameterIds: ["filter.frequency"],
      },
    ],
  });
}

export function chooseDemo(description: string): DemoConfig {
  const normalized = description.toLowerCase();
  return (
    demoConfigs.find((demo) =>
      demo.keywords.some((keyword) => normalized.includes(keyword)),
    ) ?? demoConfigs[0]!
  );
}

export const demoProposals = demoConfigs.map((config) => buildDemoProposal(config));
